# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=256)),
                ('avatar_url', models.URLField(max_length=512)),
                ('name', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=64)),
                ('user_type', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=64)),
                ('followers', models.PositiveIntegerField()),
                ('following', models.PositiveIntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repolist.Repo')),
            ],
        ),
    ]
