# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_auto_20170902_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='avatar_url',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='repo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='repolist.Repo'),
            preserve_default=False,
        ),
    ]
