# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('repo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=256)),
                ('full_name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('language', models.CharField(max_length=32)),
                ('stargazers_count', models.PositiveIntegerField()),
                ('open_issues_count', models.PositiveIntegerField()),
                ('forks_count', models.PositiveIntegerField()),
            ],
        ),
    ]
