# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='language',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
