# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repolist', '0002_auto_20170902_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
